import { BREAKPOINTS } from "../tokens";

const MOBILE = BREAKPOINTS.md;
const PORTRAIT_TABLET = BREAKPOINTS.md;
const LANDSCAPE_TABLET = BREAKPOINTS.lg;
const LAPTOP = BREAKPOINTS.xl;
const DESKTOP = BREAKPOINTS.xxl;

export { MOBILE, PORTRAIT_TABLET, LANDSCAPE_TABLET, LAPTOP, DESKTOP };
