const BTN_PRIMARY = '#3b82f6'
const BTN_PRIMARY_HOVER = '#1d4ed8'
const BTN_WARNING = '#ef4444'
const BTN_WARNING_HOVER = '#b91c1c'

export { BTN_PRIMARY, BTN_PRIMARY_HOVER, BTN_WARNING, BTN_WARNING_HOVER }